# Generated by Django 5.0.14 on 2026-08-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_otp_purpose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="purpose",
            field=models.CharField(
                choices=[("register", "Verify Registration Email")],
                max_length=20,
            ),
        ),
    ]
