# Generated by Django 5.2.17 on 2026-08-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pendingregistration_delete_otp'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='pendingregistration',
            constraint=models.UniqueConstraint(fields=('email', 'role'), name='unique_pending_email_per_role'),
        ),
        migrations.AddConstraint(
            model_name='pendingregistration',
            constraint=models.UniqueConstraint(fields=('phone_number', 'role'), name='unique_pending_phone_per_role'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email', 'role'), name='unique_user_email_per_role'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('phone_number', 'role'), name='unique_user_phone_per_role'),
        ),
    ]
