# Generated by Django 5.2.17 on 2026-08-27 06:32

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_options_alter_pendingregistration_email_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingregistration',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists for this role.'}, max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
        migrations.AddConstraint(
            model_name='pendingregistration',
            constraint=models.UniqueConstraint(fields=('username', 'role'), name='unique_pending_username_per_role'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username', 'role'), name='unique_user_username_per_role'),
        ),
    ]
