# Generated by Django 5.2.17 on 2026-08-27 06:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_store', '0002_inventoryitem_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
