# Generated by Django 5.2.17 on 2026-08-29 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customer', '0003_prescription_pharmacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('roman_ur', 'Roman Urdu'), ('mixed', 'Mixed')], default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_sessions', to='customer.customerprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('intent', models.CharField(blank=True, choices=[('medicine_search', 'Medicine Search'), ('category_browse', 'Browse Category'), ('medicine_info', 'Medicine Information'), ('image_match', 'Image Match'), ('order_status', 'Order Status'), ('general', 'General Conversation'), ('unknown', 'Unknown')], max_length=30)),
                ('detected_language', models.CharField(blank=True, max_length=10)),
                ('entities', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_medicines', models.ManyToManyField(blank=True, related_name='+', to='catalog.medicine')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_agent.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicineEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(help_text='JSON-encoded float32 embedding vector')),
                ('model_name', models.CharField(default='paraphrase-multilingual-MiniLM-L12-v2', max_length=100)),
                ('text_fingerprint', models.CharField(blank=True, help_text='SHA-256 of the source text; lets us skip re-encoding unchanged rows.', max_length=64)),
                ('image_embedding', models.JSONField(blank=True, help_text='JSON-encoded float32 image-feature vector (colour histogram + pHash).', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='catalog.medicine')),
            ],
        ),
    ]
