from django.shortcuts import get_object_or_404
from rest_framework import generics, status, viewsets
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.customer.models import Prescription
from apps.orders.models import Order, OrderStatus
from apps.orders.serializers import OrderSerializer

from . import services
from .models import DemandForecast, InventoryItem, PharmacyProfile
from .permissions import IsPharmacy
from .serializers import (
    DemandForecastSerializer,
    InventoryItemSerializer,
    PharmacyProfileSerializer,
    PrescriptionReviewSerializer,
)


def _pharmacy(request):
    return get_object_or_404(PharmacyProfile, user=request.user)


class MyPharmacyView(generics.RetrieveUpdateAPIView):
    serializer_class = PharmacyProfileSerializer
    permission_classes = [IsPharmacy]

    def get_object(self):
        profile, _ = PharmacyProfile.objects.get_or_create(
            user=self.request.user,
            defaults={"business_name": self.request.user.username, "license_number": f"TEMP-{self.request.user.id}"},
        )
        return profile


class InventoryViewSet(viewsets.ModelViewSet):
    serializer_class = InventoryItemSerializer
    permission_classes = [IsPharmacy]

    def get_queryset(self):
        return InventoryItem.objects.filter(pharmacy__user=self.request.user)

    def perform_create(self, serializer):
        serializer.save(pharmacy=_pharmacy(self.request))


class IncomingOrdersView(generics.ListAPIView):
    """Receive and review incoming orders."""

    serializer_class = OrderSerializer
    permission_classes = [IsPharmacy]

    def get_queryset(self):
        return Order.objects.filter(pharmacy__user=self.request.user).exclude(
            status__in=[OrderStatus.DELIVERED, OrderStatus.CANCELLED]
        )


class OrderTransitionView(APIView):
    """POST /api/pharmacy/orders/<id>/<action>/ where action in
    accept|preparing|ready-for-pickup|reject."""

    permission_classes = [IsPharmacy]

    ACTIONS = {
        "accept": services.accept_order,
        "preparing": services.mark_preparing,
        "ready-for-pickup": services.mark_ready_for_pickup,
    }

    def post(self, request, order_id, action):
        order = get_object_or_404(Order, id=order_id, pharmacy__user=request.user)
        if action == "reject":
            order.set_status(OrderStatus.CANCELLED, changed_by=request.user, note="Rejected by pharmacy")
        elif action in self.ACTIONS:
            self.ACTIONS[action](order, request.user)
        else:
            return Response({"detail": "Unknown action."}, status=400)
        return Response(OrderSerializer(order).data)


class VerifyPrescriptionView(APIView):
    """FR-05 + Pharmacist Copilot: approve/reject an AI-extracted prescription."""

    permission_classes = [IsPharmacy]

    def post(self, request, prescription_id):
        prescription = get_object_or_404(Prescription, id=prescription_id)
        decision = request.data.get("decision")
        notes = request.data.get("notes", "")
        if decision not in ("approved", "rejected", "needs_info"):
            return Response({"detail": "Invalid decision."}, status=400)
        prescription = services.verify_prescription(prescription, _pharmacy(request), request.user, decision, notes)
        return Response({"prescription_id": prescription.id, "status": prescription.status})


class DemandForecastView(generics.ListAPIView):
    """FR-14: pharmacy dashboard consumes forecasts generated by the AI
    service's scheduled job (G. Inventory Forecasting)."""

    serializer_class = DemandForecastSerializer
    permission_classes = [IsPharmacy]

    def get_queryset(self):
        return DemandForecast.objects.filter(pharmacy__user=self.request.user).order_by("-generated_at")
