# Generated by Django 5.2 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rider", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderprofile",
            name="address_line",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="vehicle_number",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
