# Generated by Django 5.0.14 on 2026-08-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Home', max_length=50)),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(blank=True, max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('ur', 'Urdu'), ('roman_ur', 'Roman Urdu')], default='en', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='prescriptions/%Y/%m/')),
                ('source', models.CharField(choices=[('camera', 'Camera'), ('gallery', 'Gallery'), ('pdf', 'PDF')], default='camera', max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'AI Processing'), ('needs_review', 'Needs Pharmacist Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='uploaded', max_length=20)),
                ('doctor_name', models.CharField(blank=True, max_length=150)),
                ('patient_name', models.CharField(blank=True, max_length=150)),
                ('ai_raw_response', models.JSONField(blank=True, null=True)),
                ('ai_model_version', models.CharField(blank=True, max_length=50)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_medicine_text', models.CharField(max_length=255)),
                ('strength', models.CharField(blank=True, max_length=50)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('special_instructions', models.CharField(blank=True, max_length=255)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('is_ambiguous', models.BooleanField(default=False)),
                ('pharmacist_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
