# Generated by Django 5.2.17 on 2026-08-26 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
        ('medical_store', '0002_inventoryitem_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='medical_store.pharmacyprofile'),
        ),
    ]
